{% set name = "ifermi" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ifermi-{{ version }}.tar.gz
  sha256: 9077961cde4f1803f0bb36ed8a6f2dc24d623bfff3fb4a6688b6c415873417f9

build:
  number: 0
  entry_points:
    - ifermi = ifermi.cli:cli
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - boltztrap2
    - click
    - dataclasses >=0.6
    - matplotlib-base
    - meshcut
    - monty
    - networkx
    - numpy
    - plotly
    - psutil
    - pyfftw
    - pymatgen >=2017.12.30
    - python >=3.6
    - scikit-image
    - scipy
    - spglib
    - tabulate
    - trimesh

test:
  imports:
    - ifermi
    - ifermi.tests
  commands:
    - pip check
    - ifermi --help
  requires:
    - pip

about:
  home: https://github.com/fermisurfaces/IFermi
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fermi surface generation, analysis and visualisation.
  description: |
    IFermi is a Python (3.6+) library and set of command-line tools for
    the generation, analysis, and visualisation of Fermi surfaces and
    Fermi slices. The goal of the library is to provide fully featured
    FermiSurface and FermiSlice objects that allow for easy manipulation
    and analysis.
  doc_url: https://fermisurfaces.github.io/IFermi
  dev_url: https://github.com/fermisurfaces/IFermi

extra:
  recipe-maintainers:
    - jan-janssen
